In [13]:
#Python for Data Processing
!pip install pandas openpyxl

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd

# Load the Excel file
df = pd.read_excel('C:/Users/HP/Downloads/traffic_stops.xlsx')

In [4]:
#print(df.head())        # See the first 5 rows
print(df.info())        # Check column types and missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65538 entries, 0 to 65537
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   stop_date           65538 non-null  datetime64[ns]
 1   stop_time           65538 non-null  object
 2   country_name        65538 non-null  object
 3   driver_gender       65538 non-null  object
 4   driver_age_raw      65538 non-null  int64
 5   driver_age          65538 non-null  int64
 6   driver_race         65538 non-null  object
 7   violation_raw       65538 non-null  object
 8   violation           65538 non-null  object
 9   search_conducted    65538 non-null  bool
 10  search_type         43818 non-null  object
 11  stop_outcome        65538 non-null  object
 12  is_arrested         65538 non-null  bool
 13  stop_duration       65538 non-null  object
 14  drugs_related_stop  65538 non-null  bool
 15  vehicle_number      65538 non-null  object
dtypes: bool(3), datetime64[ns](1), int64(2), object(10)
memory usage: 6.7+ MB
None

In [14]:
df = df.dropna(axis=1, how='all')
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,Unknown,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,Unknown,Ticket,True,16-30 Min,False,UP89PT2924

In [10]:
df.to_excel('cleaned_traffic_stops.xlsx', index=False)

In [15]:
#Database Design (SQL)

from sqlalchemy import create_engine

# Create SQLite DB in memory (or use 'sqlite:///traffic.db' for file)
engine = create_engine('sqlite:///traffic_stops.db')

In [17]:
import pandas as pd

# Load the cleaned dataset
df = pd.read_excel('C:/Users/HP/Downloads/cleaned_traffic_stops.xlsx')
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,vehicle_number
0,2020-01-01,00:00:00,Canada,M,59,19,Asian,Drunk Driving,Speeding,True,Vehicle Search,Ticket,True,16-30 Min,True,UP76DY3473
1,2020-01-01,00:01:00,India,M,35,58,Other,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,True,RJ83PZ4441
2,2020-01-01,00:02:00,USA,M,26,76,Black,Signal Violation,Speeding,False,Frisk,Ticket,True,16-30 Min,True,RJ32OM7264
3,2020-01-01,00:03:00,Canada,M,26,76,Black,Speeding,DUI,True,Frisk,Warning,False,0-15 Min,True,RJ76TI3807
4,2020-01-01,00:04:00,Canada,M,62,75,Other,Speeding,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,WB63BB8305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65533,2020-02-15,12:13:00,India,F,54,48,Black,Other,Other,False,Vehicle Search,Arrest,True,16-30 Min,False,DL56GW6568
65534,2020-02-15,12:14:00,Canada,F,18,35,Hispanic,Seatbelt,Other,True,Vehicle Search,Ticket,False,16-30 Min,True,TN73EO7098
65535,2020-02-15,12:15:00,USA,M,27,41,Asian,Seatbelt,DUI,True,Frisk,Ticket,True,30+ Min,True,GJ33MX8328
65536,2020-02-15,12:16:00,Canada,F,49,63,Black,Seatbelt,Other,False,Unknown,Warning,True,0-15 Min,True,KA24UZ8488
65537,2020-02-15,12:17:00,USA,F,72,32,Other,Seatbelt,Speeding,True,Unknown,Ticket,True,16-30 Min,False,UP89PT2924

In [18]:
#SQLAlchemy to Connect to MySQL

CREATE DATABASE traffic_logs;
!pip install mysql-connector-python sqlalchemy

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.3.0-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Downloading mysql_connector_python-9.3.0-cp312-cp312-win_amd64.whl (16.4 MB)
   ---------------------------------------- 0.0/16.4 MB ? eta -:--:--
   --- ------------------------------------ 1.3/16.4 MB 7.4 MB/s eta 0:00:03
   -------- ------------------------------- 3.4/16.4 MB 8.7 MB/s eta 0:00:02
   -------------- ------------------------- 5.8/16.4 MB 9.8 MB/s eta 0:00:02
   ---------------- ----------------------- 6.6/16.4 MB 8.1 MB/s eta 0:00:02
   ----------------- ---------------------- 7.1/16.4 MB 7.0 MB/s eta 0:00:02
   ------------------ --------------------- 7.6/16.4 MB 6.2 MB/s eta 0:00:02
   --------------------- ------------------ 8.7/16.4 MB 5.9 MB/s eta 0:00:02
   ----------------------- ---------------- 9.7/16.4 MB 5.8 MB/s eta 0:00:02
   ------------------------- -------------- 10.5/16.4 MB 5.7 MB/s eta 0:00:02
   --------------------------- ------------ 11.3/16.4 MB 5.5 MB/s eta 0:00:01
   ----------------------------- ---------- 12.1/16.4 MB 5.3 MB/s eta 0:00:01
   -------------------------------- ------- 13.1/16.4 MB 5.3 MB/s eta 0:00:01
   ----------------------------------- ---- 14.4/16.4 MB 5.3 MB/s eta 0:00:01
   ------------------------------------- -- 15.5/16.4 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 16.4/16.4 MB 5.2 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.3.0

In [20]:
#CREATE DATABASE traffic_logs;in sql then run the below code


from sqlalchemy import create_engine

username = 'root'
password = 'dhinesh'
host = 'localhost'        
port = '3306'             
database = 'traffic_logs'

engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}')

In [23]:
import pandas as pd
from sqlalchemy import create_engine

# -----------------------------
# Step 1: Database Credentials
# -----------------------------
username = 'root'          # Your MySQL username
password = 'dhinesh'       # Your MySQL password
host = 'localhost'         # Database host
port = '3306'              # MySQL port (default: 3306)
database = 'traffic_logs'  # Ensure this database is created manually first

# -----------------------------
# Step 2: Connect to MySQL
# -----------------------------
try:
    engine = create_engine(f'mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}')
    print("✅ MySQL connection successful.")
except Exception as e:
    print("❌ Failed to connect to MySQL:", e)
    exit()

# -----------------------------
# Step 3: Load Excel File
# -----------------------------
try:
    df = pd.read_excel('cleaned_traffic_stops.xlsx')
    print(f"✅ Loaded Excel file. {len(df)} rows ready to insert.")
except Exception as e:
    print("❌ Failed to load Excel file:", e)
    exit()

# -----------------------------
# Step 4: Insert Data to MySQL
# -----------------------------
try:
    df.to_sql('traffic_stops', con=engine, if_exists='replace', index=False)
    print("✅ Data inserted successfully into 'traffic_stops' table.")
except Exception as e:
    print("❌ Failed to insert data into MySQL:", e)

✅ MySQL connection successful.
✅ Loaded Excel file. 65538 rows ready to insert.
✅ Data inserted successfully into 'traffic_stops' table.